import 'package:version/version.dart';

/// Stable identity for one published update artifact.
///
/// The identity deliberately excludes URL query parameters because Gitee may
/// add redirect tokens to an asset URL. File names are generated by the
/// canonical artifact contract and are never taken from an HTTP response.
final class AppUpdateArtifactIdentity {
  const AppUpdateArtifactIdentity({
    required this.tag,
    required this.version,
    required this.fileName,
  });

  factory AppUpdateArtifactIdentity.fromValues({
    required String tag,
    required Version version,
    required String fileName,
  }) {
    return AppUpdateArtifactIdentity(
      tag: tag,
      version: version,
      fileName: fileName,
    );
  }

  final String tag;
  final Version version;
  final String fileName;

  String get stableKey => '$tag|$version|$fileName';

  String get stagingFileName => '$fileName.part';
}
